namespace: "gitstafette"
app:
  repositories: "537845873,478599060,168425507,587075550,583684693"
  grpcPort: 50051
  httpPort: 8080
  httpPrefix: "/"
security:
  useGeneratedCert: false
  certmanager:
    generateCert: true
    issuer:
      name: "kearos-issuer"
      kind: "ClusterIssuer"
image:
  pullPolicy: IfNotPresent
  tag: 0.1.0-e0a2c7d
imagePullSecrets:
- name: ghcr-pull-secret-2
resources:
  requests:
    cpu: 250m
    memory: 16Mi
  limits:
    memory: 32Mi
service:
  type: ClusterIP
  port: 80
fqdn: gsf-server.home.lab
fqdnWeb: gsf-server-web.home.lab
ingress:
  enabled: false
httpproxy:
  enabled: false
  ingressClassName: contour
  grpc:
    prefix: /
    protocol: h2c
  http:
    prefix: /api
    replacement: /
istio:
  enabled: true
env:
  - name: OTEL_SERVICE_NAME
    value: "GSF-Server-1"
  - name: OTEL_HOSTNAME
    value: "otel-collector-opentelemetry-collector.mon.svc.cluster.local"
  - name: OTEL_PORT
    value: "4317"

