apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gitstafette-server-test
  namespace: gitstafette
spec:
  serviceAccountName: gitstafette-server
  fetch:

  template:
  - ytt: {}
  deploy:
  - kapp: {}