apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: server.gitstafette.kearos.net.0.0.0
spec:
  refName: server.gitstafette.kearos.net
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: server.gitstafette.kearos.net
spec:
  displayName: server
  longDescription: server.gitstafette.kearos.net
  shortDescription: server.gitstafette.kearos.net

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: server
spec:
  packageRef:
    refName: server.gitstafette.kearos.net
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: server-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
