name: "gsf-relay-537845873"
namespace: "gsf"

app:
  repositories: "537845873"
  clientId: "raspi-537845873"
  extraArgs: []
  extraFlags: []

podLabels:
  app.kubernetes.io/component: "gsf-relay"
  app.kubernetes.io/part-of: "gsf-homelab"

security:
  useGeneratedCert: true
  caOnly: false
  certmanager:
    generateCert: true
    host: local-gsf-relay-537845873.home.lab
    issuer:
      name: "kearos-issuer"
      kind: "ClusterIssuer"

image:
  tag: 0.1.0-e0a2c7d

grpcServer:
  host: gsf-gsf-server.gsf.svc.cluster.local
  port: 50051
  insecureFlag: "--insecure"
  streamWindow: 60
  oauthToken:
    enabled: false
    secretName: "gistafette-client-aws-oauth"


relay:
  enabled: true
  host: "el-gitstafette-image-builds.gsf.svc.cluster.local"
  path: "/"
  healthCheckPath: "/"
  port: "8080"
  protocol: "http"
  insecure: true


resources:
  requests:
    cpu: 250m
    memory: 32Mi
  limits:
    memory: 128Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - arm64

env:
  - name: OTEL_SERVICE_NAME
    value: "GSF-Client-1"
  - name: OTEL_HOSTNAME
    value: "otel-collector-opentelemetry-collector.mon.svc.cluster.local"
  - name: OTEL_PORT
    value: "4317"

discovery:
  enabled: true
  image:
    tag: "0.5.1-client-alpine"
  hostname: "gsf-gsf-discovery.gsf.svc.cluster.local"
  env:
    - name: OTEL_SERVICE_NAME
      value: "GSF-Discovery-1"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector-opentelemetry-collector.mon.svc.cluster.local:4317"