{{ if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "server.fullname" . }}
spec:
  hosts:
    - {{ .Values.httpproxy.fqdn }}
  gateways:
    - {{ include "server.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: {{ include "server.fullname" . }}
{{- end }}