#@ if data.values.httpproxy.enabled:
{{ if .Values.httpproxy.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: : {{ .Values.name  }}
  labels:
    app.kubernetes.io/name: {{ include "discovery.fullname" . }}
  {{- with .Values.httpproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.httpproxy.ingressClassName  }}
  routes:
    - conditions:
        - prefix: {{ .Values.httpproxy.grpc.prefix }}
      services:
        - name: {{ include "discovery.fullname" . }}
          port: {{ .Values.app.grpcPort  }}
          protocol: {{ .Values.httpproxy.grpc.protocol  }}
    - conditions:
        - prefix: {{ .Values.httpproxy.http.prefix  }}
      services:
        - name: {{ include "discovery.fullname" . }}
          port: {{ .Values.service.port  }}
      pathRewritePolicy:
        replacePrefix:
          - replacement: {{ .Values.httpproxy.http.replacement  }}
  virtualhost:
    fqdn:  {{ .Values.fqdn }}
    {{ if .Values.security.useGeneratedCert }}
    tls:
      secretName: {{ include "tls.secretName" . }}
    {{ end}}
{{ end}}